#pragma checksum "..\..\..\Printing\wpfProducts.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "3051A277D28B568D2CFCA05526D278D7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Edge.Tower2.UI;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Edge.Tower2.UI.Printing {
    
    
    /// <summary>
    /// wpfProductMenu
    /// </summary>
    public partial class wpfProductMenu : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 6 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Edge.Tower2.UI.Printing.wpfProductMenu Me;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdMain;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas cvsMain;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLogin;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblLogin;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ScrollViewer2;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView ListView2;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblOperator;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCustomer;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_ScrollDown;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_ScrollUp;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ScrollViewerR;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgViewer;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas cvsKeyBoard;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgKeyboard_bg;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Edge.Tower2.UI.UC_Keyboard UC_Keyboard1;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtOperator;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtCustomer;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSet;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\Printing\wpfProducts.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas cvsEnterInfo;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Edge.Tower2.UI;component/printing/wpfproducts.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Printing\wpfProducts.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Me = ((Edge.Tower2.UI.Printing.wpfProductMenu)(target));
            return;
            case 2:
            this.grdMain = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.cvsMain = ((System.Windows.Controls.Canvas)(target));
            return;
            case 4:
            this.btnLogin = ((System.Windows.Controls.Button)(target));
            
            #line 39 "..\..\..\Printing\wpfProducts.xaml"
            this.btnLogin.Click += new System.Windows.RoutedEventHandler(this.btnLogin_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.lblLogin = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            
            #line 48 "..\..\..\Printing\wpfProducts.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.PrintButton_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ScrollViewer2 = ((System.Windows.Controls.ScrollViewer)(target));
            
            #line 52 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewer2.PreviewMouseMove += new System.Windows.Input.MouseEventHandler(this.ScrollViewer2_PreviewMouseMove);
            
            #line default
            #line hidden
            
            #line 52 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewer2.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ScrollViewer2_PreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 52 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewer2.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ScrollViewer2_MouseLeave);
            
            #line default
            #line hidden
            
            #line 52 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewer2.PreviewMouseUp += new System.Windows.Input.MouseButtonEventHandler(this.ScrollViewer2_PreviewMouseUp);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ListView2 = ((System.Windows.Controls.ListView)(target));
            
            #line 54 "..\..\..\Printing\wpfProducts.xaml"
            this.ListView2.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Selector_OnSelectionChanged);
            
            #line default
            #line hidden
            
            #line 54 "..\..\..\Printing\wpfProducts.xaml"
            this.ListView2.ManipulationBoundaryFeedback += new System.EventHandler<System.Windows.Input.ManipulationBoundaryFeedbackEventArgs>(this.ManipulationBoundaryFeedbackHandler);
            
            #line default
            #line hidden
            return;
            case 11:
            this.lblOperator = ((System.Windows.Controls.Label)(target));
            
            #line 84 "..\..\..\Printing\wpfProducts.xaml"
            this.lblOperator.PreviewMouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.lblOperator_PreviewMouseDoubleClick);
            
            #line default
            #line hidden
            
            #line 84 "..\..\..\Printing\wpfProducts.xaml"
            this.lblOperator.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.lblOperator_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 12:
            this.lblCustomer = ((System.Windows.Controls.Label)(target));
            
            #line 85 "..\..\..\Printing\wpfProducts.xaml"
            this.lblCustomer.PreviewMouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.lblCustomer_PreviewMouseDoubleClick);
            
            #line default
            #line hidden
            
            #line 85 "..\..\..\Printing\wpfProducts.xaml"
            this.lblCustomer.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.lblCustomer_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btn_ScrollDown = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\..\Printing\wpfProducts.xaml"
            this.btn_ScrollDown.Click += new System.Windows.RoutedEventHandler(this.btn_ScrollDown_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.btn_ScrollUp = ((System.Windows.Controls.Button)(target));
            
            #line 89 "..\..\..\Printing\wpfProducts.xaml"
            this.btn_ScrollUp.Click += new System.Windows.RoutedEventHandler(this.btn_ScrollUp_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.ScrollViewerR = ((System.Windows.Controls.ScrollViewer)(target));
            
            #line 94 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewerR.PreviewMouseMove += new System.Windows.Input.MouseEventHandler(this.ScrollViewerR_PreviewMouseMove);
            
            #line default
            #line hidden
            
            #line 94 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewerR.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ScrollViewerR_PreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 94 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewerR.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ScrollViewerR_MouseLeave);
            
            #line default
            #line hidden
            
            #line 94 "..\..\..\Printing\wpfProducts.xaml"
            this.ScrollViewerR.PreviewMouseUp += new System.Windows.Input.MouseButtonEventHandler(this.ScrollViewerR_PreviewMouseUp);
            
            #line default
            #line hidden
            return;
            case 16:
            this.imgViewer = ((System.Windows.Controls.Image)(target));
            return;
            case 17:
            this.cvsKeyBoard = ((System.Windows.Controls.Canvas)(target));
            return;
            case 18:
            this.imgKeyboard_bg = ((System.Windows.Controls.Image)(target));
            return;
            case 19:
            this.UC_Keyboard1 = ((Edge.Tower2.UI.UC_Keyboard)(target));
            return;
            case 20:
            this.txtOperator = ((System.Windows.Controls.TextBox)(target));
            
            #line 105 "..\..\..\Printing\wpfProducts.xaml"
            this.txtOperator.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.txtOperator_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 21:
            this.txtCustomer = ((System.Windows.Controls.TextBox)(target));
            
            #line 107 "..\..\..\Printing\wpfProducts.xaml"
            this.txtCustomer.PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.txtCustomer_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 22:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            
            #line 110 "..\..\..\Printing\wpfProducts.xaml"
            this.btnBack.Click += new System.Windows.RoutedEventHandler(this.btnBack_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.btnSet = ((System.Windows.Controls.Button)(target));
            
            #line 111 "..\..\..\Printing\wpfProducts.xaml"
            this.btnSet.Click += new System.Windows.RoutedEventHandler(this.btnSet_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.cvsEnterInfo = ((System.Windows.Controls.Canvas)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 9:
            
            #line 69 "..\..\..\Printing\wpfProducts.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SlowerButton_OnClick);
            
            #line default
            #line hidden
            break;
            case 10:
            
            #line 76 "..\..\..\Printing\wpfProducts.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.tbk_Description_MouseDown);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

